version: '3'

services:
  api:
    build: .
    restart: always
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      - NODE_ENV=dev
    links:
      - db
    ports:
      - "8000:8000"
  db:
      image: aashreys/mongo-auth:latest
      environment:
        - AUTH=yes
        - MONGODB_ADMIN_USER=root
        - MONGODB_ADMIN_PASS=toor
        - MONGODB_APPLICATION_DATABASE=poslovna
        - MONGODB_APPLICATION_USER=dev
        - MONGODB_APPLICATION_PASS=dev123
      volumes:
        - dbdatavolume:/data/db
      ports:
        - "27017:27017"

volumes:
  dbdatavolume: